// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.29.3

package protobuf;

public final class DemoProto {
    private DemoProto() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
            com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
            /* major= */ 4,
            /* minor= */ 29,
            /* patch= */ 3,
            /* suffix= */ "",
            DemoProto.class.getName());
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_Demo_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internal_static_Demo_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\ndemo.proto\".\n\004Demo\022\n\n\002id\030\001 \001(\005\022\014\n\004code" +
                "\030\002 \001(\t\022\014\n\004name\030\003 \001(\tB\027\n\010protobufB\tDemoPr" +
                "otoP\001b\006proto3"
        };
        descriptor                              = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                });
        internal_static_Demo_descriptor         =
            getDescriptor().getMessageTypes().get(0);
        internal_static_Demo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_Demo_descriptor,
            new java.lang.String[] {"Id", "Code", "Name",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
