// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: demo.proto
// Protobuf Java Version: 4.29.3

package protobuf;

public interface DemoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Demo)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 自身属性
     * </pre>
     *
     * <code>int32 id = 1;</code>
     *
     * @return The id.
     */
    int getId();

    /**
     * <code>string code = 2;</code>
     *
     * @return The code.
     */
    java.lang.String getCode();

    /**
     * <code>string code = 2;</code>
     *
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
    getCodeBytes();

    /**
     * <code>string name = 3;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 3;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
